const WALLETCONNECT_PROJECT_ID = process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID || '';

if (!WALLETCONNECT_PROJECT_ID) {
  throw new Error('WALLETCONNECT_PROJECT_ID is required');
}

export { WALLETCONNECT_PROJECT_ID };
