export const PrivateLendingIngressAbi = [
  {
    inputs: [{ internalType: "address", name: "mailbox", type: "address" }],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "depositId", type: "bytes32" },
      { indexed: true, internalType: "address", name: "depositor", type: "address" },
      { indexed: false, internalType: "address", name: "token", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
      { indexed: false, internalType: "bool", name: "isNative", type: "bool" },
    ],
    name: "DepositCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "encryptedDataHash", type: "bytes32" },
    ],
    name: "EncryptedActionProcessed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "encryptedDataHash", type: "bytes32" },
    ],
    name: "EncryptedActionReceived",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "address", name: "_hook", type: "address" }],
    name: "HookSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "uint8", name: "version", type: "uint8" }],
    name: "Initialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "address", name: "_ism", type: "address" }],
    name: "IsmSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "token", type: "address" },
      { indexed: false, internalType: "uint256", name: "totalDeposited", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "totalReserved", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "totalBorrowed", type: "uint256" },
    ],
    name: "LiquidityUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "previousOwner", type: "address" },
      { indexed: true, internalType: "address", name: "newOwner", type: "address" },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint256", name: "oldRatio", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "newRatio", type: "uint256" },
    ],
    name: "ReserveRatioUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "depositId", type: "bytes32" },
      { indexed: true, internalType: "address", name: "depositor", type: "address" },
      { indexed: false, internalType: "address", name: "token", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
      { indexed: false, internalType: "bool", name: "isNative", type: "bool" },
    ],
    name: "WithdrawUnused",
    type: "event",
  },
  {
    inputs: [],
    name: "PACKAGE_VERSION",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    name: "actionIdToCiphertextHash",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    name: "actionToDepositId",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    name: "actions",
    outputs: [
      { internalType: "address", name: "sender", type: "address" },
      { internalType: "uint32", name: "destinationDomain", type: "uint32" },
      { internalType: "uint256", name: "dispatchedAt", type: "uint256" },
      { internalType: "bool", name: "acknowledged", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    name: "ciphertextHashToActionId",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "token", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "depositErc20",
    outputs: [{ internalType: "bytes32", name: "depositId", type: "bytes32" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "depositNative",
    outputs: [{ internalType: "bytes32", name: "depositId", type: "bytes32" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    name: "deposits",
    outputs: [
      { internalType: "address", name: "depositor", type: "address" },
      { internalType: "address", name: "token", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "bool", name: "isNative", type: "bool" },
      { internalType: "bool", name: "released", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "domains",
    outputs: [{ internalType: "uint32[]", name: "", type: "uint32[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint32", name: "_domain", type: "uint32" },
      { internalType: "bytes32", name: "_router", type: "bytes32" },
    ],
    name: "enrollRemoteRouter",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint32[]", name: "_domains", type: "uint32[]" },
      { internalType: "bytes32[]", name: "_addresses", type: "bytes32[]" },
    ],
    name: "enrollRemoteRouters",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "encryptedDataHash", type: "bytes32" }],
    name: "getActionIdByCiphertextHash",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "token", type: "address" }],
    name: "getAvailableLiquidity",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "token", type: "address" }],
    name: "getLiquidityInfo",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "totalDeposited", type: "uint256" },
          { internalType: "uint256", name: "totalReserved", type: "uint256" },
          { internalType: "uint256", name: "totalBorrowed", type: "uint256" },
        ],
        internalType: "struct PrivateLendingIngress.TokenLiquidity",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint32", name: "_origin", type: "uint32" },
      { internalType: "bytes32", name: "_sender", type: "bytes32" },
      { internalType: "bytes", name: "_message", type: "bytes" },
    ],
    name: "handle",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "hook",
    outputs: [{ internalType: "contract IPostDispatchHook", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "interchainSecurityModule",
    outputs: [{ internalType: "contract IInterchainSecurityModule", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "liquidity",
    outputs: [
      { internalType: "uint256", name: "totalDeposited", type: "uint256" },
      { internalType: "uint256", name: "totalReserved", type: "uint256" },
      { internalType: "uint256", name: "totalBorrowed", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "localDomain",
    outputs: [{ internalType: "uint32", name: "", type: "uint32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "mailbox",
    outputs: [{ internalType: "contract IMailbox", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "reserveRatio",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint32", name: "_domain", type: "uint32" }],
    name: "routers",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_hook", type: "address" }],
    name: "setHook",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_module", type: "address" }],
    name: "setInterchainSecurityModule",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "newRatio", type: "uint256" }],
    name: "setReserveRatio",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint32", name: "destinationDomain", type: "uint32" },
      { internalType: "bytes32", name: "depositId", type: "bytes32" },
      { internalType: "bytes", name: "ciphertext", type: "bytes" },
    ],
    name: "submitAction",
    outputs: [{ internalType: "bytes32", name: "actionId", type: "bytes32" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint32", name: "_domain", type: "uint32" }],
    name: "unenrollRemoteRouter",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint32[]", name: "_domains", type: "uint32[]" }],
    name: "unenrollRemoteRouters",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
